name: forlet_marketplace_ng
description: "ForLet Marketplace NG Flutter Project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  font_awesome_flutter: ^10.8.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  page_transition: ^2.2.1
  provider: ^6.1.5
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/categories/
    - assets/images/splash_screen/
  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf
    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
